serlo/cloudflare-worker

- __tests__/frontend-proxy.ts
- __tests__/index.ts
- __tests__/maintenance.ts
- __tests__/static-pages.tsx
- __tests__/utils.tsx
- jest.setup.ts
- src/frontend-proxy.ts
- src/index.ts
- src/kv.d.ts
- src/maintenance/index.tsx
- src/utils.tsx
- src/vars.d.ts
- wrangler.toml
Fixes https://github.com/serlo/frontend/issues/78
> Add proxy for frontend

- __tests__/api.ts
- __tests__/frontend-proxy.ts
- src/api/index.ts
- src/frontend-proxy.ts
- src/secrets.d.ts
* Sign API requests
* Requests to `/spenden` resolve to default backend (Fixes https://github.com/serlo/frontend/issues/164 )
> Fix bugs in frontend proxy

- __tests__/frontend-proxy.ts
- src/frontend-proxy.ts
* `/search` always resolve to frontend (fixes https://github.com/serlo/frontend/issues/248)
* `/spenden` always resolve to frontend (after https://github.com/serlo/frontend/issues/170 got implemented)
* requests for authentication resolve to default backend (fixes #18 )
I'll merge it into #19 with better code for testing...
> Update frontend proxy

- __tests__/_helper.ts
- __tests__/auth.ts
- __tests__/frontend-proxy.ts
- __tests__/static-pages.tsx
- src/auth/index.ts
- src/frontend-proxy/index.ts
- src/index.ts
- src/instance.ts
- src/static-pages/index.tsx
- src/url-utils.ts
- src/vars.d.ts
- wrangler.toml
- **auth**. Add `https://serlo.org/auth/frontend-redirect-uris.json` for https://openid.net/specs/openid-connect-registration-1_0.html#SectorIdentifierValidation.
- **frontend-proxy**. Add var `REDIRECT_AUTHENTICATED_USERS_TO_LEGACY_BACKEND` that decides whether authenticated users should be redirected to the legacy backend (current behavior). With this, we can already test frontend authentication on staging environment.
- **frontend-proxy**.  Resolve `/api/auth/*` to frontend.
- **frontend-proxy**. Pass query string to backend.
> prepare cloudflare worker for frontend auth

- __tests__/frontend-proxy.ts
- src/frontend-proxy.ts
- yarn.lock
Fixes a bug when requests to the frontend contains a trailing slash (Fixes #43 ). Also `yarn upgrade` was executed so that `prismjs` gets updated.
> frontend: Remove trailing slashes in frontend requests

- __tests__/index.ts
- src/index.ts
@inyono As discussed here is the hotfix so that the cloudflare-worker accepts url encoded and non url encoded alias of api.serlo.org
> redirects: Handle URL- and non-URL-encoded aliases

- __tests__/utils.tsx
- jest.setup.ts
- src/utils.tsx
Fixes #55 
Idea: When the cache key has more than 512 characters the sha-1 hash of it is taken. I would use the sha-1 hash because then we have no collision for longer keys (e.g. two paths which are so long that they are the same for the first 512 characters).
> utils: Reduce max cache key to 512 characters

- __tests__/_helper.ts
- __tests__/api.ts
- __tests__/frontend-proxy.ts
- __tests__/index.ts
- __tests__/utils.tsx
- jest.setup.ts
I tried to comment on the code but it somehow doesnt allow me 
on Frontend-proxy.ts
Line 563 : function apiToReturnError() {
mockApi(global.API_ENDPOINT, (_req, res, ctx) => res(ctx.status(404)))
}
My thinking was to change the mockApi function in the helper and add a "|| resolver" so that the function as it is written can work. 
and in utils.tsx
line 262:
i tried to create a apiUuid function that was similar to the returnUuid and which takes Mockedrequest as first argument and Uuid as second
> Tried to add the resolver to mockApi

- README.md
- __tests__/embed.ts
- src/embed.ts
- src/index.ts
@kulla what do you think of the inline image code solution? Seemed nicer that to store image assets in the worker.
Other options include
- storing the placeholder in the frontend (redirecting the request to the frontend)
- or returning an error header and letting the frontend decide how to handle missing images.
Merge whenever you want.
(issue: #66)
> WIP: Preview images via embed.serlo.org

- __tests__/__utils__/index.ts
- __tests__/frontend-proxy.ts
- __tests__/maintenance.ts
- __tests__/static-pages.tsx
- src/frontend-proxy.ts
- src/index.ts
Resolves the bug that `/spenden` is redirecting to `/21565/spenden` because there is still an old page. Due to the new alias system a redirect would be triggered. It also implements the logic that `/spenden` is treated like `/search` (where the cookie determines the backend).
> No redirect for /spenden 

- .eslintrc.js
- scripts/maintenance.ts
See https://eslint.org/docs/rules/no-console: So we can detect leftover console log statements before merging into master. `scripts/maintenance.ts` seems to be a legacy script with no purpose which I want to delete in a follow-up PR.
> Add eslint rule "no-console"

- src/embed.ts
Currently wikimedia thumbnails like http://localhost:8787/thumbnail?url=https://upload.wikimedia.org/wikipedia/commons/1/15/Inerter_vibration_isolation_experiment.webm cannot be loaded since wikimedia responses with `429 Too many requests`. I add cache setting to see whether it helps...
> Add caching setting when fetching Wikimedia thumbnails

- package.json
- yarn.lock
Adds https://www.npmjs.com/package/ts-unused-exports to show unused exports in the source code. @inyono What do you think about this tool? I tend to add it in other projects as well...
> Add "yarn show-unused-exports"

- __tests__/__utils__/expect-helper.ts
- __tests__/assets.ts
- __tests__/embed.ts
- __tests__/frontend-proxy.ts
- __tests__/utils.tsx
This makes the test more robust since this value should not differ
between requests (the original file stays the same). Google seems to
convert the image to other formats based on the user agent and probably
other things.
Other changes: https://github.com/serlo/serlo.org-cloudflare-worker/commit/880fc77979e581d55d90de236d1f0d7c022663ed and https://github.com/serlo/serlo.org-cloudflare-worker/pull/231/commits/04972ae8405f338cd2cb46098d277f515b98190a (explanations in commit messages)
> Fix assets tests: Use header "x-goog-stored-content-length"

- __tests__/__utils__/kv.ts
- package.json
- src/bindings.d.ts
- yarn.lock
Closes https://github.com/serlo/serlo.org-cloudflare-worker/issues/242
This PR uses https://github.com/cloudflare/workers-types/pull/178 in order to delete the old `KV` interface. Thus `createKV` needed to be extended (each not implemented function returns an error).
> Use KVNamespace instead of KV

- __tests__/__utils__/services/api.ts
- package.json
- src/redirects.ts
- yarn.lock
Removes the dependency of ramda since it was used rarely. This should also make the build smaller and reduces the overall complexety of maintenance a little bit.
> Remove dependency "ramda"

- __tests__/__utils__/services/frontend.ts
- __tests__/__utils__/services/serlo.ts
- __tests__/frontend-proxy.ts
- src/frontend-proxy.ts
- src/utils/vercel-frontend-proxy.ts
fix for https://github.com/serlo/frontend/issues/1500
if we actually deploy `use-legacy editor` tomorrow I guess it's okay to have this bug until then.
> handle `add-revision-old` as well

- __tests__/frontend-proxy.ts
- src/utils/vercel-frontend-proxy.ts
Deployed already in staging...
> Forward /taxonomy/create to frontend only in GET (fixes #277)

- __tests__/redirects.ts
- src/redirects.ts
in notification mails there are links of this format `/discussion/{commentId}`
@kulla after the redirect will they be handled by the cf-worker logic again?
So would `/discussion/65395` after this PR will lead the user to `/mathe/1573/vektor#comment-65395`?
> feat: add support for old comment link format

- __tests__/__utils__/test-environment.ts
- __tests__/api.ts
- jest.setup.ts
- src/api.ts
`Access-Control-Allow-Origin` can only have three values: *, \<origin\> or null (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin), that's why we have to dynamically set the origin for the subdomains.
It's quite impossible to receive a browser request from origin 'htt<span>ps://serlo.org', but I didn't want to risk it, so I also set it to positively respond for this origin.
Since localhost frontend makes request via server side function we don't have to cover its case.
> feat: API - CORS best practice

- package.json
Follow up of #427 : Otherwise node always shows a warning that ESM is experimental.
> test: Add `--no-warnings` in `yarn test`

- __tests__/utils.tsx
- src/utils/index.tsx
This function is nowhere used in the production code
> refactor: Remove unused function createEmptyBodyResponse()

- __tests__/__utils__/test-environment.ts
- src/index.ts
- src/utils/sentry.ts
Clean up of the following warning:
```
[WARNING] The entrypoint src/index.ts has exports like an ES Module, but hasn't defined a default export like a module worker normally would. Building the worker using "service-worker" format...
```
Followed the documentation in https://developers.cloudflare.com/workers/learning/migrate-to-module-workers/#migrate-a-simple-worker to use ES modules format.
--- 
Fixes #430
> Update worker format
