README.md, src/static-pages/config.ts
Fixes https://github.com/serlo/serlo.org-legal/issues/2
=> Update English privacy policy

__tests__/frontend-proxy.ts, __tests__/url-utils.ts, src/frontend-proxy.ts, src/url-utils.ts, wrangler.toml
Changed things:
* Set probability to 10%
* Fix bug #21 (content api)
* Refactor `__test__/url-utils.ts` and `src/url-utils.ts`
* Remove header `X-SERLO-API`
=> Improvements / Fixes for frontend-proxy and setting prod probability to 10%

README.md, __tests__/frontend-proxy.ts, __tests__/utils.tsx, src/frontend-proxy.ts, src/utils.tsx
See https://github.com/serlo/serlo.org-cloudflare-worker/issues/24
=> frontend: Feature to set frontend domain via cookie

__stories__/static-pages.tsx, __tests__/_helper.ts, __tests__/static-pages.tsx, jest.setup.ts, src/auth/index.ts, src/instance.ts, src/static-pages/config.ts, src/static-pages/index.tsx, src/ui/template.tsx, src/utils.tsx, yarn.lock
* Fixes #30 (merge `Instance` and `LanguageCode`)
* Remove ununsed function `expectContentTypeIsJson`
* Use `createJsonResponse` in `src/auth/index.ts`
* Run `yarn upgrade` (so that #33 can be deleted)
* Fix remaining lint errors
=> Follow up of #28

src/utils.tsx
=> utils: Update query in getPathInfo()

__tests__/frontend-proxy.ts, src/frontend-proxy/index.ts
Fixes https://github.com/serlo/serlo.org-cloudflare-worker/issues/38
=> frontend: Authenticated users get legacy backend for some special paths

__tests__/frontend-proxy.ts, src/frontend-proxy.ts
Fixes https://github.com/serlo/serlo.org-cloudflare-worker/issues/46
=> frontend: Set cookie "useFrontend" for all subdomains

__tests__/index.ts, __tests__/utils.tsx, src/index.ts, src/utils.tsx
See https://github.com/serlo/api.serlo.org/issues/80 (same fix for cloudflare worker)
=> redirects: Catch error in decoding paths

src/static-pages/config.ts
@kulla: this will revert any changes you made to other environments that haven't been merged to master yet. So you might need to redeploy some stuff if necessary.
=> Update privacy policy

__tests__/__utils__/expect-helper.ts, __tests__/__utils__/index.ts, __tests__/__utils__/mock-helper.ts, __tests__/api.ts, __tests__/auth.ts, __tests__/frontend-proxy.ts, __tests__/index.ts, __tests__/maintenance.ts, __tests__/static-pages.tsx, __tests__/utils.tsx, jest.setup.ts, src/index.ts, src/utils/index.tsx, yarn.lock
This PR contains some improvements before I work on https://github.com/serlo/serlo.org-cloudflare-worker/issues/73 where I improve also the tests. So that I can use those improvements there. These are:
* Fix a lint error in `jest.setup.ts`
* Use `__tests__/__utils__` like in api.serlo.org
* Remove code to handle unencoded aliases from the api
* Fixes https://github.com/serlo/serlo.org-cloudflare-worker/issues/69 and thus also fixes https://github.com/serlo/serlo.org-cloudflare-worker/issues/59
* Run `yarn upgrade`
=> Implementation of some improvements

__tests__/__utils__/kv.ts, __tests__/__utils__/mock-helper.ts, __tests__/__utils__/services/api.ts, __tests__/__utils__/services/database.ts, __tests__/__utils__/services/index.ts, __tests__/__utils__/services/stats.ts, __tests__/__utils__/services/utils.ts, __tests__/api.ts, __tests__/frontend-proxy.ts, __tests__/index.ts, __tests__/maintenance.ts, __tests__/static-pages.tsx, __tests__/utils.tsx, jest.setup.ts
First steps to improve our tests (see https://github.com/serlo/serlo.org-cloudflare-worker/issues/76 ):
* Fixes https://github.com/serlo/serlo.org-cloudflare-worker/issues/61
* Fixes https://github.com/serlo/serlo.org-cloudflare-worker/issues/79
=> Improvements for the tests

__tests__/__utils__/services/api.ts, __tests__/frontend-proxy.ts, src/frontend-proxy.ts, src/index.ts
Fixes https://github.com/serlo/serlo.org-cloudflare-worker/issues/73
=> Resolve special paths of frontend before redirecting

__tests__/index.ts, src/index.ts
I added the redirect for meet and meet/dev.
=> Added the meet redirect

__tests__/frontend-proxy.ts, src/frontend-proxy.ts, src/index.ts
Fixes https://github.com/serlo/serlo.org-cloudflare-worker/issues/86
=> frontend: Add support for /license/detail/:id

__tests__/__utils__/services/database.ts, __tests__/index.ts, src/index.ts, src/utils/index.tsx
Fixes https://github.com/serlo/serlo.org-cloudflare-worker/issues/70
=> redirects: Redirect also to correct instance

src/index.ts
The tests are still giving errors, but I think that's independent of my work
=> switch instead of ifelse

wrangler.toml
closes #99
~~merge after https://github.com/serlo/frontend/pull/711 is merged~~
(Frontend is ready)
=> Frontend (production): Probability to 25, support for more types

__tests__/__utils__/services/database.ts, __tests__/redirects.ts
=> Fix e2e tests in __tests__/redirects.ts

__tests__/__utils__/fetch-helper.ts, __tests__/__utils__/services/utils.ts, __tests__/embed.ts, src/embed.ts
=> embed.serlo.org: support for providers

wrangler.toml, yarn.lock
Ping https://github.com/serlo/frontend/issues/780
=> FRONTEND_PROBABILITY_MOBILE = "0.50"

__tests__/embed.ts
The images changes a little bit which youtube or wikimedia return. Thus
I implemented a check that the content length does not differ from an
expected value by a maximal relative error.
=> Fix e2e tests in embed.ts

__tests__/embed.ts, src/embed.ts
* Remove the TaskEither monad in getVimdeoThumbnail()
* Test whether returned image is actually an image
=> Some improvements for src/embed.ts

wrangler.toml, yarn.lock
Ping https://github.com/serlo/frontend/issues/780
=> FRONTEND_PROBABILITY_DESKTOP = "0.50"

wrangler.toml
Ping https://github.com/serlo/frontend/issues/780
=> FRONTEND_PROBABILITY_DESKTOP = "0.75"

wrangler.toml
=> FRONTEND_PROBABILITY_DESKTOP = "1"

__tests__/utils.tsx, src/kv.d.ts, src/utils/index.tsx
Closes https://github.com/serlo/serlo.org-cloudflare-worker/issues/57
=> Add refinement type CacheKey

__tests__/frontend-proxy.ts, src/frontend-proxy.ts
Closes https://github.com/serlo/serlo.org-cloudflare-worker/issues/161
=> /___graphql forwards always to new frontend

README.md, __tests__/__utils__/test-environment.ts, package.json
Follow up of https://github.com/serlo/serlo.org-cloudflare-worker/commit/074e8428ba77e6250bca586a92f29b5f1754eadd
=> Remove dev environment

__tests__/frontend-proxy.ts, src/frontend-proxy.ts
Closes https://github.com/serlo/serlo.org-cloudflare-worker/issues/165
=> serlo.org/disable-frontend also works with PROBABILITY=1

__tests__/redirects.ts, src/redirects.ts
Fixes https://github.com/serlo/serlo.org-cloudflare-worker/issues/184
=> Redirect /entity/view/<id>/toc to /<id>

__tests__/frontend-proxy.ts, src/frontend-proxy.ts
Closes https://github.com/serlo/serlo.org-cloudflare-worker/issues/181
=> Redirect to legacy when header X-From is legacy-serlo.org

__tests__/index.ts, src/index.ts
=> Disallow robots in staging via robots.txt for all subdomains

__tests__/__utils__/services/database.ts, __tests__/redirects.ts, src/utils/index.tsx
test in redirect.ts concerning comment only works locally, not in production
=> redirect of comment to article added

__tests__/redirects.ts, src/redirects.ts
Closes #200 Sorry Botho for the confusion! Maybe you could take a look at my solution instead?
=> Added redirect for fundraising

src/redirects.ts
=> refactor meet redirects

__tests__/redirects.ts, src/redirects.ts
Closes https://github.com/serlo/serlo.org-cloudflare-worker/issues/183
=> Add redirect: serlo.org/global -> en.serlo.org/global

__tests__/redirects.ts, src/redirects.ts
Closes https://github.com/serlo/frontend/issues/1114
=> Add redirect /user/public -> /user/me

__tests__/redirects.ts, src/redirects.ts
Closes https://github.com/serlo/serlo.org/issues/655
=> Redirect /page/view/:id to /:id

__tests__/redirects.ts, src/redirects.ts
=> add pdf redirect

__tests__/__utils__/expect-helper.ts, __tests__/embed.ts, src/embed.ts, src/utils/sentry.ts
=> Add sentry reports to src/embed

__tests__/utils.tsx, package.json, src/are-we-edtr-io-yet/index.tsx, src/bindings.d.ts, src/embed.ts, src/legal-pages/index.tsx, src/metadata-api.ts, src/pdf-proxy.ts, src/quickbar-proxy.ts, src/utils/index.tsx, src/utils/sentry.ts, tsconfig.json, yarn.lock
Add the project https://github.com/cloudflare/workers-types and remove unecessary type definitions afterwards. Changes:
* Remove fetchWithCache() -> has IMHO no advantage to a direct call to fetch with `cf`
* Remove unnecessary type definitions and type casts
* Add sentry reportings of headings
=> Add @cloudflare/worker-types

__tests__/__utils__/services/frontend.ts, __tests__/frontend-proxy.ts, src/utils/url.ts
@kulla this should solve a small inconsistency with CSR in the frontend and the CF-Worker frontent proxy.
=> add event history user route

__tests__/__utils__/services/frontend.ts, __tests__/frontend-proxy.ts, src/frontend-proxy.ts, src/redirects.ts, src/utils/url.ts
Open questions: 
- "AB" case is not well defined -> need help with proper definiton
- I added property "pathPrefix" to route types in order to distinguish two cases. It's not very elegant. Any better ideas?
=> frontendProxy and frontendSpecialPaths refactored

__tests__/lenabi.ts, src/lenabi/redirects.ts, yarn.lock
Deployed to staging & production already.
=> lenabi: update redirects

scripts/run_all_checks.sh, src/frontend-proxy.ts
trying again… this seems a lot simpler :)
=> allow `user/settings` as frontend route 

__tests__/__utils__/services/frontend.ts, __tests__/__utils__/services/serlo.ts, __tests__/frontend-proxy.ts, src/frontend-proxy.ts, src/utils/vercel-frontend-proxy.ts
=> frontend editor by default; useLegacyEditor cookie

src/frontend-proxy.ts
can be deployed to staging after review.
might even be save to deploy to production. not sure :)
=> add de subject landing pages

src/frontend-proxy.ts, src/utils/vercel-frontend-proxy.ts
@kulla this would be useful for testing in staging.
Thank you 🙏
=> Use frontend for newly migrated routes

__fixtures__/robots.ts, __tests__/index.ts, src/index.ts
=> serve robots.txt in production

src/frontend-proxy.ts
Can be deployed in staging.
Thanks!
=> tax sort in frontend

__tests__/assets.ts, src/index.ts
See https://github.com/serlo/api.serlo.org/pull/709
=> feat: Support new filenames for assets.serlo.org

src/frontend-proxy.ts
=> feat: Forward /jobs/* to new frontend

src/auth.ts
=> auth: add language trait to kratos identity schema

__tests__/api.ts, src/api.ts
since cloudflare is not keeping cors as it comes from the api.
=> API: Set dynamic CORS

src/frontend-proxy.ts
=> fix: Forward "/entity/repository/compare/" to frontend

src/frontend-proxy.ts
=> fix: fix 500 in kratos email links

src/embed.ts
=> fix: Add caching for GeoGebraAPIRequests

__tests__/frontend-proxy.ts, src/frontend-proxy.ts
=> fix: Forward /term/create to frontend in production

__tests__/index.ts, __tests__/robots.ts, src/index.ts, src/robots.ts
I guess it is better to consolidate everything which is related to handling of `robots.txt` requests to an extra file.
=> refactor: Create src/robots.ts

.github/workflows/js.yml, README.md
Fixes #392 
--- 
Additionally, update the [README.md](README.md) file.
=> Upgrade GitHub Actions

package.json
"wrangler publish" is deprecated
=> Use "wrangler deploy" instead of "wrangler publish"

package.json
"wrangler publish" is deprecated
=> chore: Use "wrangler deploy"

wrangler.toml
=> fix: Add zone_id to wrangler
